---
title: "Testing"
output: html_document
external_link: ""
image: 
  caption: ''
  preview_only: yes
summary: A bar plot showing support for QAnon among different generations
tags:
- Deep Learning
url_code: ""
url_pdf: ""
url_slides: ""
url_video: ""
---





```{r, include=FALSE}
#Loading the necessary packages
library(rio)
library(tidyverse)
library(ggplot2)
library(ggridges)
library(ggsci)
library(ggthemes)
library(car)
library(gridExtra)
#install.packages("ggpubr")
library(ggpubr)
#install.packages("showtext")
library(showtext)
#install.packages("prediction")
library(prediction)
font_add_google("Merriweather", "M", regular.wt = 400)
font_add_google("Josefin Sans", "JS", regular.wt = 400)
font_add_google("EB Garamond", "G", regular.wt = 400)
font_add_google("Raleway", "Rw", regular.wt = 400)
font_add_google("Averia Sans Libre", "Ave", regular.wt = 400)
font_add_google("Nova Round", "Nova", regular.wt = 400)
font_add_google("Carrois Gothic", "CG", regular.wt=400)
font_add_google("Jost", "Jost", regular.wt=400)
showtext_opts(dpi = 300)
showtext_auto(enable = TRUE)
#install.packages("devtools")
library(devtools)
#install_github("ryanburge/socsci")
library(socsci)
#install.packages("paletteer")
library(paletteer)
#install.packages("jtools")
library(jtools)
#install.packages("interactions")
library(interactions)
#install.packages("patchwork")
library(patchwork)
#install.packages("psych")
library(psych)
#install.packages("MASS")
library(MASS)
#install.packages("ragg")
library(ragg)
#install.packages("systemfonts")
library(systemfonts)
#install.packages("gtools")
library(gtools)
library(margins)
library(interactions)

```

```{r, include=FALSE}
#Data import
library(readr)
O20_with_weights <- read_csv("~/Downloads/O20_with_weights.csv")

O20 <- O20_with_weights

O20 <- O20 %>% filter(gc==1)

rm(O20_with_weights)


```

```{r, include=FALSE}
#Making the generations (cohorts) variable
O20 <- O20 %>% mutate(age=2020-q3_1,
                      birthyr=q3_1)

O20 <- O20 %>% mutate(cohorts = frcode(birthyr>= 1901 & birthyr <= 1924 ~ 'Greatest\nGeneration',
                                       birthyr>= 1925 & birthyr <= 1945 ~ 'Silent\nGeneration',
                                       birthyr>= 1946 & birthyr <= 1964 ~ 'Boomers',
                                       birthyr>= 1965 & birthyr <= 1976 ~ 'Gen X',
                                       birthyr>= 1977 & birthyr <= 1995 ~ 'Millennials',
                                       birthyr>= 1996 & birthyr <= 2020 ~ 'Gen Z'))

#Making QAnon variable
O20 <- O20 %>% mutate(q38_10r=6-q38_10)
O20 <- O20 %>% mutate(q38_10rc=car::recode(q38_10r, "1:3=0; 4:5=1")) 
O20 <- O20 %>% mutate(q38_10lab=frcode(q38_10rc==0 ~ "Disagree",
                                       q38_10rc==1 ~ "Agree"))




```

```{r, include=FALSE}
#Making tropes variable
O20 <- O20 %>%mutate(q107_1r=car::Recode(q107_1, "1=1; 2=0"))
O20 <- O20 %>%mutate(q107_2r=car::Recode(q107_2, "1=1; 2=0"))
O20 <- O20 %>%mutate(q107_3r=car::Recode(q107_3, "1=1; 2=0"))
O20 <- O20 %>%mutate(q107_4r=car::Recode(q107_4, "1=1; 2=0"))
O20 <- O20 %>%mutate(q107_5r=car::Recode(q107_5, "1=1; 2=0"))
O20 <- O20 %>%mutate(q107_6r=car::Recode(q107_6, "1=1; 2=0"))
O20 <- O20 %>%mutate(q107_7r=car::Recode(q107_7, "1=1; 2=0"))
O20 <- O20 %>%mutate(q107_8r=car::Recode(q107_8, "1=1; 2=0"))

O20 <- O20 %>% rowwise() %>% mutate(tropes=sum(q107_1r, 
                                               q107_2r, 
                                               q107_3r,
                                               q107_4r, 
                                               q107_5r, 
                                               q107_6r, 
                                               q107_7r, 
                                               q107_8r, na.rm=TRUE)) %>% ungroup()
O20 <- O20 %>% mutate(tropes_factor=as.factor(tropes))

```

```{r}
#Bar Plot for each generations support of QAnon
O20 %>% 
  group_by(cohorts) %>% filter(cohorts!="NA") %>% 
  ct(q38_10lab, wt=wgt) %>% 
  ggplot(., aes(x=reorder(cohorts, pct), y=pct, fill=q38_10lab)) + 
  geom_col(alpha=.8, color="black", width = .75, position = position_dodge2()) + 
  theme_hc() +
  theme(text=element_text(family="JS", size=12),
        legend.position = "right",
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=.5, color="gray80"),
        axis.text.x = element_text(size=9),
        plot.title = element_text(hjust = .5)) +
  geom_text(aes(y=(pct+.025), label = round(pct*100, digits=2)), family="JS",
            position = position_dodge(width = .75)) +
  scale_y_continuous(labels=percent_format(accuracy=1)) +
  labs(x="", y="", 
       title="Millennials and Gen X'ers Have the Highest QAnon Support",
       caption="Source: October 2020 Survey; @JDenn0514") +
  scale_fill_manual(name="QAnon Supporter?", 
                    labels=c("Disagree", "Agree"), 
                    values = c("#FF6F00FF", "#C71000FF"))

```



